services:
  sportgo-go:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    env_file: .env
    ports:
      - "$PORT:$PORT"
    depends_on:
      - mongodb
      - postgres

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_DB_PASS
    ports:
      - "$MONGO_DB_PORT:$MONGO_DB_PORT"
    volumes:
      - mongodb:/data/db
      
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - "$POSTGRES_DB_PORT:$POSTGRES_DB_PORT"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_DB_PASS
      - POSTGRES_DB=$POSTGRES_DB_NAME

volumes:
  mongodb:
  postgres:
